[[module.imports]]
path = "github.com/hbstack/footer"

[params.hugopress.modules.hb-footer-beian.hooks.hb-footer-site-info-end]
cacheable = true
weight = 1

[params.hb.footer.beian]
# number = "x公网安备xxxxxxxxxxxxxx号"
# icp_number = "xICP备xxxxxxxx号"
